### ISSUE TITLE
RSS feed broken

### ISSUE THREAD

**Issue by gtallen1187** [keithfma/keithfma.github.io#4]
Hey @keithfma!  I just found out about your blog through the LinkedIn post - I love it!  So much so that i went to subscribe, and was unfortunately greeted by an error page on when attempting to access the XML feed.  You can [view the error here](http://www.allnans.com/feed.xml).

Love the blog!

**Comment by keithfma** [comment]
Thanks Greg! Turned out to be some silly little config syntax error. Looks OK to me now.
